### ISSUE TITLE
[Feature Request] Add an option to sort files in folders based on TG_AUTHORIZED_USER_IDs

### ISSUE THREAD

**Issue by Frunner20** [jsavargas/telethon_downloader#11]
Hello!
Your application has proven itself incredibly useful.

Would it be possible to add an option to sort files in folders based on TG_AUTHORIZED_USER_IDs?
I have multiple telegram groups to which my bot belongs to. I imagine it would be hard to know where each file came from in the near future.

Thanks in advance,
FRunner20.

**Comment by jsavargas** [comment]
Dear, I added a new environment variable "TG_FOLDER_BY_AUTHORIZED = True" in the develop tag.
for you to try

**Comment by Frunner20** [comment]
It works! Though there is one problem: if the sent file is one of extentions that are stored in separate folders (jpg,pdf,mp3...), it gets put in that folder and doesnt get sorted.
It would be absolutely wonderful if you could fix this.

**Comment by jsavargas** [comment]
arreglado, y he agregado un archivo de configuracion, donde puedes cambiar las rutas para  x usuarios

![image](https://user-images.githubusercontent.com/6886410/130284820-17601ffc-1e05-4c2b-bd8a-71bdedb94da8.png)
