### ISSUE TITLE
Installed version of yt-dlp does not work with current YouTube API

### ISSUE THREAD

**Issue by brianara3** [jsavargas/telethon_downloader#31]
When trying to download videos from YouTube you get the error below. This is resolved in the current release of yt-dlp (2023.03.03).

`Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

You also can't update to the current version of yt-dlp due to running an outdated version of Python (<3.7). This is also noted in the deprecation warning on start of downloads.

`DeprecationWarning: Support for Python version 3.6 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/3764  for more details. You will no longer receive updates on this version! Please update to Python 3.7 or above`

Manually forcing the upgrade of Python to 3.8 and reinstalling the pip modules allows the app to work fine and downloads complete. However, these manual changes are overwritten on docker reloads using your container (I'm using the Unraid CA version).

**Comment by jsavargas** [comment]
Thank you very much for the report, yes... It is an error that I already have present and I have a version in develop waiting to finish the tests to pass it to master

**Comment by jsavargas** [comment]
I made a server in discord, to be able to unify the projects that I am working on in one place and that among the same users doubts are resolved and improve little by little with the improvements that can be proposed, if you want to join, I leave you I leave the link

https://discord.gg/nPDb2YsBfP
