### ISSUE TITLE
[Request] Skip files from queue

### ISSUE THREAD

**Issue by GuillerVks** [jsavargas/telethon_downloader#38]
Hi,
I want to suggest a enhancement (TG_SKIP_TORRENT_PARALLEL=true/false), create an environment variable to skip from queue the Torrent files.
i.e: If i configure the queue limit to 1, and i send 1gb file and also i send a torrent file. The torrent file can't be added to a watch folder beacuse have to wait the first file finish. I think.. that is a totally unnecessary wait for add a torrent file.

Thanks.

**Comment by jsavargas** [comment]
It is a good feature, I will make it skip the queue and download automatically
