### ISSUE TITLE
[Issue] High CPU usage while downloading

### ISSUE THREAD

**Issue by systemerror-codenotfound** [jsavargas/telethon_downloader#39]
I'm running this on Docker on Unraid in a HP G8 microserver with a E31260L  CPU

I'm detecting a high CPU usage while downloading, it takes around 60-80% of cpu per download, so if i try to launch 2 downloads at the same time, my cpu will be at 100% all the time during the download

On htop all i can see is  a process with the command python3 /app/botorrent.py

On the docker log there is nothing special, just a info message that the download was started.

I'm running this on Unraid 6.12.2 

On the docker app it's installed Python 3.11.2

**Comment by pablogpr** [comment]
The same thing happens to me on a G7

**Comment by scrhall** [comment]
The same thing happens to me on a G7

**Comment by jsavargas** [comment]
The same thing happens to me, but it is while it is downloading the files, once downloaded it releases the resources.  And it's not overuse either.  I'll still do tests with Python, maybe the use of resources can be improved.
