### ISSUE TITLE
ERROR: TimedOutError downloading : RPCError -503: Timedout (caused by GetFileRequest)

### ISSUE THREAD

**Issue by Felisuk** [jsavargas/telethon_downloader#50]
Since few week this error shows sometimes when I try to download file, not always it doesn´t matter if I´m trying to download 1 or 2 files at the same time or the channel I´m trying to download files. 
Could be a problem related to telegram bot new update? Thanks in advance.

**Comment by Reister777** [comment]
Same issue here...
[2023-12-31 15:19:20,973] CRITICAL RPCError -503: Timedout (caused by GetFileRequest)
[2023-12-31 15:19:20,973] INFO    [EXCEPCION]: RPCError -503: Timedout (caused by GetFileRequest)

Could we add an option to retry automatically? # #

**Comment by Felisuk** [comment]
I update telethon library and It seems to work well again.

**Comment by goliath888** [comment]
Same here. 

@Felisuk What did you do exactly?

**Comment by Koradris** [comment]
Same error

**Comment by Felisuk** [comment]
I updated library with this comands:
pip install --upgrade telethon
python3 -m pip install --upgrade telethon.

Unfortunately after several test error shows again.

**Comment by Koradris** [comment]
> I updated library with this comands: pip install --upgrade telethon python3 -m pip install --upgrade telethon.
> 
> Unfortunately after several test error shows again.

Can i use this command in unraid ?

**Comment by Felisuk** [comment]
I´m not sure.

**Comment by Reister777** [comment]
the only workaround I found is forward the same file again and again and most of the times, it resumes the download (except one or two files I had to download them using the Android Telegram App...)

**Comment by Koradris** [comment]
Let's hope the maintainer can fix it.
so it is difficult to use

**Comment by dsz79** [comment]
same issue, resend the file dont work.

**Comment by Felisuk** [comment]
@jsavargas Thanks for the effort.

**Comment by jsavargas** [comment]
@Felisuk You're welcome, I have updated the Telethon dependency to its latest version and the problem has been solved, improvements are coming soon

**Comment by Reister777** [comment]
Indeed it is working perfectly now. Thank you very much @jsavargas !

**Comment by dsz79** [comment]
thx!!!
