### ISSUE TITLE
How to auto download new posts?

### ISSUE THREAD

**Issue by EEB9** [jsavargas/telethon_downloader#66]
How can I automatically download the new content in a public telegram channel? I'm so tired of manually saving files a few times a day.

**Comment by jsavargas** [comment]
Telegram bots cannot read messages from other groups, for that I have another project, but it is not completely finished, I did it for that very reason, to edit some videos from a Telegram channel and I uploaded it in case it could be useful to someone else . Now I'm working on another one that does the same thing, using other libraries.
