### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by Nightclue7897** [jsavargas/telethon_downloader#69]
![Screenshot (2)](https://github.com/user-attachments/assets/366c4c85-d123-48c2-8fce-9f905267f70a)
 Traceback (most recent call last):
  File "/app/bottorrent.py", line 1184, in <module>
    bot = TelegramBot()
  File "/app/bottorrent.py", line 78, in __init__
    self.constants.get_variable("TG_AUTHORIZED_USER_ID")
AttributeError: 'bool' object has no attribute 'replace'

**Comment by Nightclue7897** [comment]
i have also tried with my user id but also same

**Comment by jsavargas** [comment]
In that variable goes your user ID, you must have some error or the bot must not have permissions to send messages, since it works for everyone, tell me if you already solved it
