### ISSUE TITLE
Very slow download speed

### ISSUE THREAD

**Issue by drmetro09** [jsavargas/telethon_downloader#73]
Is there any way to increase the download speed , the download speed is very very slow

**Comment by jsavargas** [comment]
Yes, it seems to be a problem with the telethon library, I have another project that is the same as this one, but it uses another library and it is much faster, if you want to try it

https://github.com/jsavargas/telegram-downloader

**Comment by drmetro09** [comment]
Do i have to install it as separate docker container or changing the tag and name will help?

**Comment by drmetro09** [comment]
I don’t want to create another bot as its tedious process , can you update the same faster library for this project… because this one is very very very slow

**Comment by drmetro09** [comment]
> You should be able to change the docker and work without problems, I have thought about updating this, but it would no longer be telethon, I am waiting for the telethon library to be updated to see if times improve.

I tried to change the image to telegram_downloader but this doesn’t work

**Comment by drmetro09** [comment]
I tried the new telegram-downloader but this is also slow and csn you please explain what is the group path and how to I assign it to the files ( forward files)

**Comment by drmetro09** [comment]
Also if we add the bot to a group it doesn’t work

**Comment by jsavargas** [comment]
> it is also not using the tmp directory like telethon downloader used to do and how do i stop downloading the file once it is sent to the bot ?

Neither of the two bots stops downloading the file once you send it, I don't know if that is possible with the telethon and pyrogram libraries

**Comment by jsavargas** [comment]
![image](https://github.com/user-attachments/assets/50f452ad-0a4e-4574-877a-05c2091f45e8)

Only 45 seconds to download 137mb

**Comment by drmetro09** [comment]
Yes , its faster as compared to telethon_downloader bot
