### ISSUE TITLE
Nueva variable para archivos temporales

### ISSUE THREAD

**Issue by djchoyr** [jsavargas/telethon_downloader#9]
Una nueva variable para cambiar la carpeta de archivos temporales. No es un problema como tal, pero sería tremendamente interesante para algunos dispositivos. 

Excelente trabajo y gracias por el esfuerzo

**Comment by jsavargas** [comment]
podrias especificar mas?
hay una variable, esta escondida por que al final la defini en /download, pero se podria trabajar en ella

**Comment by djchoyr** [comment]
Me refiero a una “ environment variables” en el docker donde poder definir la localización del archivo temporal de las descargas. Sería interesante, al menos desde mi punto se vista, que la localización de los temporales pudiese ser diferente de la localización final de los archivos. Podríamos ganar velocidad de descarga en equipos como las raspberry

**Comment by jsavargas** [comment]
aaaah, entiendo; te refieres a la carpea tmp?

si, podria agregarlo en una nueva version.>

que se puedan definir
tmp
download
completed
torrent

**Comment by djchoyr** [comment]
Muchas gracias. Es todo un detalle. Excelente trabajo 👍👍👍
